# Site settings
title:       "The Honest Guide to Cooking"
email:       "stridlinnea@gmail.com"
author:      "Linnea Strid"
description: "The Honest Guide to Cooking - a somewhat comprehensive guide to the ingredients, equipment and technique needed to make food."
url:         "http://honestguidetocooking.com"

# Authors
authors:
  linnea:
    name: "Linnea Strid"
    display_name: "Linnea Strid"
    email: linnea@seriousfox.co.uk
    twitter: babolili
    active: ""

# Google analytics
google_analytics: 'UA-63176802-1'

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons

show_social_icons: true
github_username: babolili
stackoverflow_id:
twitter_username: babolili

google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

#Assets

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/webfonts
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  css_compressor: sass
  cachebust: none
  cache: false
  debug: false

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     12
sass:
  compressed: true

gems:
  - jekyll-last-modified-at

#rake boilerplate 
ingredient:
  template: _ingredient.txt
  extension: md
equipment:
  template: _equipment.txt
  extension: md
tipstricks:
  template: _tipstricks.txt
  extension: md
techniques:
  template: _techniques.txt
  extension: md
savedinner:
  template: _savedinner.txt
  extension: md
general:
  template: _general.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
